[build]
  publish = "dist"
  command = "npm run build"

[template]
  required-extensions = ["supabase"]

[[headers]]
  for = "/images/nfl/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/images/coaches/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"